---
name: Continuous Integration Build
on:
  push:
    branches:
      - master

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install JDK 1.8
        uses: joschi/setup-jdk@v1.0.0
        with:
          java-version: 'openjdk8'
          architecture: 'x32'

      - name: Build 
        run: java -cp java HelloWorldApp
#      - name: Build with Maven
#        run: mvn -B clean install --file pom.xml



