---
name: Continuous Integration Build
on:
  push:
    branches:
      - master

jobs:
  build_java8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: '8.0.x'
          java-package: jdk
          architecture: x86

      - name: Build 
        run: java -cp java HelloWorldApp
#      - name: Build with Maven
#        run: mvn -B clean install --file pom.xml



